Add App Startup library
PatilShreyas/permission-flow-android pull request #20
Opened 2022-08-02 09:30 UTC by dev-weiqi

First of all thank you for this awesome project.
I added [App Startup](https://developer.android.com/topic/libraries/app-startup) library in this project and the user don't need to initialize manually anymore!
Also I fixed the build issues (I'm not native speaker, sorry for any grammatical mistakes)

- [x] ./gradlew build -> BUILD SUCCESSFUL 
- [x] ./gradlew spotlessApply -> BUILD SUCCESSFUL

2022-08-03 16:19 UTC, PatilShreyas requested changes
@dev-weiqi Thanks for the PR, it's really nice 😃. Here are some comments.

2022-08-03 16:19 UTC, PatilShreyas commented on README.md
> -Before using any API of the library, it needs to be initialized before.
Do not remove this section. Instead, we should explain that this library automatically gets initialized with the App Startup library. So if someone disables the initializer (_to provide their own coroutine dispatcher_), there should be a proper resource for them to refer to.

2022-08-03 16:19 UTC, PatilShreyas commented on permission-flow/src/main/java/dev/shreyaspatil/permissionFlow/PermissionFlow.kt
> +        internal val DEFAULT_DISPATCHER = Executors.newFixedThreadPool(2).asCoroutineDispatcher()
Keep it private. Do not change this

2022-08-03 16:19 UTC, PatilShreyas commented on permission-flow/src/main/java/dev/shreyaspatil/permissionFlow/PermissionFlow.kt
> +        @Deprecated(message = "We don't need to call `init()` in this version.", level = DeprecationLevel.HIDDEN)
This method shouldn't be marked as deprecated, this is still needed to be able to configure the dispatcher.

2022-08-03 16:19 UTC, PatilShreyas commented on permission-flow/src/main/java/dev/shreyaspatil/permissionFlow/initializer/PermissionFlowInitializer.kt
> +        PermissionFlowImpl.init(context, PermissionFlow.DEFAULT_DISPATCHER)
This method is overloaded already, no need to provide a default dispatcher already. 

```suggestion
        PermissionFlowImpl.init(context)
```

2022-08-03 16:19 UTC, PatilShreyas commented on permission-flow/src/main/java/dev/shreyaspatil/permissionFlow/utils/ApiLevelChecker.kt
> +internal object ApiLevelChecker {
This is nice addition 👍🏻

2022-08-03 16:21 UTC, PatilShreyas commented
@dev-weiqi CodeCov is failing due to coverage impact, could you please add basic tests for the initializer?

2022-08-07 06:40 UTC, dev-weiqi commented on README.md
> -Before using any API of the library, it needs to be initialized before.
Done. 
Thanks for the suggestion, learn a lot😀

2022-08-07 06:40 UTC, dev-weiqi commented on permission-flow/src/main/java/dev/shreyaspatil/permissionFlow/PermissionFlow.kt
> +        internal val DEFAULT_DISPATCHER = Executors.newFixedThreadPool(2).asCoroutineDispatcher()
Done.

2022-08-07 06:41 UTC, dev-weiqi commented on permission-flow/src/main/java/dev/shreyaspatil/permissionFlow/initializer/PermissionFlowInitializer.kt
> +        PermissionFlowImpl.init(context, PermissionFlow.DEFAULT_DISPATCHER)
Done.

2022-08-07 06:41 UTC, dev-weiqi commented on permission-flow/src/main/java/dev/shreyaspatil/permissionFlow/utils/ApiLevelChecker.kt
> +internal object ApiLevelChecker {
I was using the wrong JDK version 😱 , I think we don't need this class anymore.

2022-08-08 06:27 UTC, PatilShreyas commented on README.md
> -Before using any API of the library, it needs to be initialized before.
Nice

2022-08-08 06:40 UTC, PatilShreyas requested changes

2022-08-08 06:40 UTC, PatilShreyas commented on README.md
> +If you want to provide own coroutine dispatcher
Don't say "_If you want to provide own coroutine dispatcher_". Instead say, "If you want to initialize manually". Also suggest them to remove the initializer provider from the Manifest.

```xml
<provider
    android:name="androidx.startup.InitializationProvider"
    android:authorities="${applicationId}.androidx-startup"
    android:exported="false"
    tools:node="merge">
    
    <meta-data
        android:name="dev.shreyaspatil.permissionFlow.initializer.PermissionFlowInitializer"
        android:value="androidx.startup"
        tools:node="remove" />
 </provider>
```

Remove the below section of "Disable PermissionFlowInitializer in AndroidManifest.xml" and keep it here only

2022-08-08 06:40 UTC, PatilShreyas commented on README.md
> +        PermissionFlow.init(this, permissionDispatcher)
Just provide `Dispatchers.IO` in the example. Keep it simple and small as possible

2022-08-08 06:40 UTC, PatilShreyas commented on README.md
> +                Manifest.permission.ACCESS_FINE_LOCATION,
Fix indentations

2022-08-08 06:40 UTC, PatilShreyas commented on permission-flow/src/test/java/dev/shreyaspatil/permissionFlow/initializer/PermissionFlowInitializerTest.kt
> +}
Good work here 👍🏻

2023-04-08 18:06 UTC, merged